env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  project:
    - ./mod/tsconfig.json
    - ./plugins/tsconfig.json
plugins:
  - '@typescript-eslint'
  - 'only-warn'
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
  no-duplicate-imports: "error"
  "@typescript-eslint/strict-boolean-expressions": "error"
  "@typescript-eslint/consistent-type-imports":
    - error
    - {
      prefer: 'type-imports',
      fixStyle: 'inline-type-imports',
    }
